--DATA RECOVERY SESSION:

--Checking data retention time in Snowflake. Check Retention_time column
CREATE DATABASE POC_TEST;
CREATE SCHEMA DBO;

CREATE TABLE POC_TEST(ID INT, NAME VARCHAR(20));


INSERT INTO POC_TEST VALUES(1, 'TOM');
INSERT INTO POC_TEST VALUES(2, 'CATHY');
INSERT INTO POC_TEST VALUES(3, 'MERLIN');
INSERT INTO POC_TEST VALUES(4, 'JEREMY');
INSERT INTO POC_TEST VALUES(5, 'ELENA');
INSERT INTO POC_TEST VALUES(6, 'STEVE');


SHOW DATABASES;

SHOW SCHEMAS;

SHOW TABLES;


USE DATABASE POC_TEST;
ALTER DATABASE POC_TEST SET DATA_RETENTION_TIME_IN_DAYS=7;


SELECT TABLE_NAME, RETENTION_TIME 
FROM INFORMATION_SCHEMA.TABLES

--Which all tables do not support Time travel/data retention in Snowflake
-External tables/Temporary TABLES
-Views as views do not store any data of themselves
-Stage/Stream tables (used to capture cdc) are not considered as permanent TABLES
-System tables/Snowflake managed tables do not have retention time as they do not have user data.
-Zero Retention Setting
	
--Creating backup/clone of user database
CREATE DATABASE POC_TEST_BACKUP CLONE POC_TEST;

DROP DATABASE POC_TEST_BACKUP; -- We can still see the dropped database through SHOW DATABASES HISTORY;

--Cloning Schema 
CREATE SCHEMA DBO_BACKUP CLONE POC_TEST.DBO;

SELECT * FROM POC_TEST;

SELECT CURRENT_TIMESTAMP;
--2024-09-16 13:39:17.167 -0400

UPDATE POC_TEST SET NAME=NULL WHERE NAME ='JEREMY';

--INSERT INTO POC_TEST
SELECT * FROM POC_TEST
BEFORE(TIMESTAMP=>'2024-09-16 13:39:17.167 -0400':: TIMESTAMP_LTZ); --BEFORE THIS TIME

SELECT * FROM POC_TEST
AT (TIMESTAMP=>'2024-09-16 13:39:17.167 -0400':: TIMESTAMP_LTZ); -- AT STATEMENT IS INCLUSIVE OF THE STATE OF DATA.

--DELETE STATEMENT. MAKE SURE TO COPY THE QUERY ID OF THE STATEMENT BEING RUN.

DELETE FROM POC_TEST;

QUERY ID --> 01B712EA-0001-355F-0001-CD4600A8CEB6 (WE CAN CHECK THIS FROM QUERY HISTORY AS WELL)
SELECT * FROM POC_TEST;

SELECT * FROM POC_TEST
BEFORE( STATEMENT =>'01B712EA-0001-355F-0001-CD4600A8CEB6');

SELECT * FROM POC_TEST
AT( STATEMENT =>'01B712EA-0001-355F-0001-CD4600A8CEB6');


--TIME TRAVEL THROUGH OFFSET.

SELECT * FROM POC_TEST;
AT(OFFSET=>-300);

DROP DATABASE POC_TEST;

UNDROP DATABASE POC_TEST;

USE DATABASE POC_TEST;
SELECT * FROM POC_TEST

USE DATABASE POC_TEST;