--  Set Role and Warehouse
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

--Create database
CREATE OR REPLACE DATABASE SNOWFLAKE_POC;

--Create Schema
CREATE OR REPLACE SCHEMA SNOWFLAKE_POC.DBO;


--  Create Data Warehouses
CREATE OR REPLACE WAREHOUSE WH_SNOWFLAKE_POC
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  MAX_CLUSTER_COUNT = 3
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  -- RESOURCE_MONITOR = RM_SNOWFLAKE_POC_WH
  COMMENT = 'Warehouse Snowflake_POC';

 
 --GRANT USAGE ON WAREHOUSE WH_SNOWFLAKE_POC TO ROLE FR_SNOWFLAKE_POC;
 --GRANT MONITOR ON WAREHOUSE WH_SNOWFLAKE_POC TO ROLE FR_SNOWFLAKE_POC;
--Creating an access role
CREATE ROLE AR_SNOWFLAKE_POC;

--Creating an FR Role
CREATE ROLE FR_SNOWFLAKE_POC;

--Granting role FR role to Snowflake_BI
GRANT ROLE FR_SNOWFLAKE_POC TO ROLE SNOWFLAKE_BI;

--GRANTING AR ROLE TO FR ROLE
GRANT ROLE AR_SNOWFLAKE_POC TO ROLE FR_SNOWFLAKE_POC;


--Granting the account Sysadmin Access
GRANT USAGE ON DATABASE SNOWFLAKE_POC TO ROLE AR_SNOWFLAKE_POC;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SNOWFLAKE_POC TO ROLE AR_SNOWFLAKE_POC;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SNOWFLAKE_POC TO ROLE AR_SNOWFLAKE_POC;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT OPERATE ON ALL TASKS IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
GRANT OPERATE ON FUTURE TASKS IN SCHEMA SNOWFLAKE_POC.DBO TO ROLE AR_SNOWFLAKE_POC;
-- ADDITIONAL COMMANDS WOULD BE NEEDED FOR CICD  WORK
-- PERMISSIONS FOR INTEGRATIONS, STAGES, FILE FORMATS, STREAMS

--CREATING  RESOURCE MONITORS REQUIRES ACCOUNTADMIN 

USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE RESOURCE MONITOR RM_SNOWFLAKE_POC_WH WITH
  CREDIT_QUOTA = 50
  FREQUENCY = DAILY
  START_TIMESTAMP = IMMEDIATELY
  --  END_TIMESTAMP = NEVER    -- Default is no end date
  --  SNOWFLAKEDEV is local ACCOUNTADMIN with "DBA_Alerts@SUNWING.CA" set for the email
  NOTIFY_USERS = ( 'ADM_AHALI@SUNWING.CA', 'SNOWFLAKEDEV' )
  TRIGGERS ON 110 PERCENT DO SUSPEND_IMMEDIATE
    ON 90 PERCENT DO SUSPEND
    ON 75 PERCENT DO NOTIFY;

--  Assign Resource Monitors to the different Warehouses
ALTER WAREHOUSE IF EXISTS WH_SNOWFLAKE_POC
	SET RESOURCE_MONITOR = RM_SNOWFLAKE_POC_WH;

--GRANTING USAGE AND MONITOR TO FR_SNOWFLAKE_POC ON WAREHOUSE
USE ROLE SECURITYADMIN;
 GRANT USAGE ON WAREHOUSE WH_SNOWFLAKE_POC TO ROLE FR_SNOWFLAKE_POC;
 GRANT MONITOR ON WAREHOUSE WH_SNOWFLAKE_POC TO ROLE FR_SNOWFLAKE_POC;


